// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teocuitla.Shared.Data;

#nullable disable

namespace Teocuitla.Web.Migrations
{
    [DbContext(typeof(TeocuitlaDbContext))]
    [Migration("20260625135800_AddProductImageSupport")]
    partial class AddProductImageSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Teocuitla.Shared.Models.CatalogoSitio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("EstrategiaEvasion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IntervaloMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SelectorImagenXPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SelectorNombreXPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SelectorPrecioXPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SelectorProductoXPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SelectorStockXPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UltimoRastreo")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlBase")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Catalogo_Sitios");
                });

            modelBuilder.Entity("Teocuitla.Shared.Models.HistorialPrecio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("EnStock")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCaptura")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("VarianteComercialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("FechaCaptura")
                        .HasDatabaseName("IX_HistorialPrecios_FechaCaptura");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("FechaCaptura"), false);

                    b.HasIndex("VarianteComercialId", "FechaCaptura")
                        .HasDatabaseName("IX_HistorialPrecios_VarianteId_FechaCaptura_Clustered");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("VarianteComercialId", "FechaCaptura"));

                    b.ToTable("Historial_Precios");
                });

            modelBuilder.Entity("Teocuitla.Shared.Models.ProductoMaestro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Productos_Maestros");
                });

            modelBuilder.Entity("Teocuitla.Shared.Models.RegistroFallaScraping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstrategiaEvasion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaFalla")
                        .HasColumnType("datetime2");

                    b.Property<string>("HtmlContenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProxyUtilizado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlProducto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("VarianteComercialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VarianteComercialId");

                    b.ToTable("Registro_Fallas_Scraping");
                });

            modelBuilder.Entity("Teocuitla.Shared.Models.RegistroProxy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Baneado")
                        .HasColumnType("bit");

                    b.Property<int>("FallosAcumulados")
                        .HasColumnType("int");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LatenciaMs")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Puerto")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoUso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Registro_Proxies");
                });

            modelBuilder.Entity("Teocuitla.Shared.Models.VarianteComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CatalogoSitioId")
                        .HasColumnType("int");

                    b.Property<bool>("EnStock")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaUltimoIntento")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("IntentosDiaActual")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("PrecioActual")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("PrecioAnterior")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductoMaestroId")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlProducto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogoSitioId");

                    b.HasIndex("ProductoMaestroId");

                    b.HasIndex("Sku")
                        .HasDatabaseName("IX_VariantesComerciales_Sku");

                    b.ToTable("Variantes_Comerciales");
                });

            modelBuilder.Entity("Teocuitla.Shared.Models.HistorialPrecio", b =>
                {
                    b.HasOne("Teocuitla.Shared.Models.VarianteComercial", "VarianteComercial")
                        .WithMany("HistorialPrecios")
                        .HasForeignKey("VarianteComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VarianteComercial");
                });

            modelBuilder.Entity("Teocuitla.Shared.Models.RegistroFallaScraping", b =>
                {
                    b.HasOne("Teocuitla.Shared.Models.VarianteComercial", "VarianteComercial")
                        .WithMany()
                        .HasForeignKey("VarianteComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VarianteComercial");
                });

            modelBuilder.Entity("Teocuitla.Shared.Models.VarianteComercial", b =>
                {
                    b.HasOne("Teocuitla.Shared.Models.CatalogoSitio", "CatalogoSitio")
                        .WithMany()
                        .HasForeignKey("CatalogoSitioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Teocuitla.Shared.Models.ProductoMaestro", "ProductoMaestro")
                        .WithMany("Variantes")
                        .HasForeignKey("ProductoMaestroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogoSitio");

                    b.Navigation("ProductoMaestro");
                });

            modelBuilder.Entity("Teocuitla.Shared.Models.ProductoMaestro", b =>
                {
                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("Teocuitla.Shared.Models.VarianteComercial", b =>
                {
                    b.Navigation("HistorialPrecios");
                });
#pragma warning restore 612, 618
        }
    }
}
